### ISSUE TITLE
Pypresence not working if discord not installed or logged in

### ISSUE THREAD

**Issue by dan2762** [GDcheeriosYT/Gentrys-Quest-Python#64]
```Traceback (most recent call last):
  File "main.py", line 63, in <module>
  File "testing\TestingHandler.py", line 32, in start
  File "Interface\Interfaces\Testing\Game\TestGameInterface.py", line 17, in __init__
  File "Game.py", line 67, in __init__
  File "Online\API\Presence\Presence.py", line 8, in __init__
  File "pypresence\presence.py", line 45, in connect
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "pypresence\baseclient.py", line 121, in handshake
pypresence.exceptions.DiscordError: Error Code: 1000 Message: User logged out
[11392] Failed to execute script 'main' due to unhandled exception!```

**Comment by GDcheeriosYT** [comment]
Just Fixed it! Thanks for the letting me know!
